// Centralized Font Awesome icon imports. Page-level files should import
// from here rather than reaching into the FA packages directly so we have
// one place to see what icons are in use and to swap variants.

export {
  faBars,
  faXmark,
  faCheck,
  faSpinner,
  faChevronUp,
  faChevronDown,
  faChevronRight,
  faChevronLeft,
  faFolderOpen,
  faCirclePlay,
  faCirclePause,
  faCircleQuestion,
  faCircleInfo,
  faCircleCheck,
  faCircleExclamation,
  faCircleXmark,
  faTriangleExclamation,
  faUpload,
  faDownload,
  faSun,
  faMoon,
  faRightFromBracket,
  faGear,
  faCopy,
  faTrash,
  faPenToSquare,
  faPlus,
  faMinus,
  faMagnifyingGlass,
  faRotate,
  faEye,
  faEyeSlash,
  faArrowUpRightFromSquare,
} from "@fortawesome/free-solid-svg-icons";
