// Centralized Font Awesome icon imports. Page-level files should import
// from here rather than reaching into the FA packages directly so we have
// one place to see what icons are in use and to swap variants.

export {
  // Existing chrome / control icons.
  faBars,
  faXmark,
  faCheck,
  faSpinner,
  faChevronUp,
  faChevronDown,
  faChevronRight,
  faChevronLeft,
  faFolderOpen,
  faCirclePlay,
  faCirclePause,
  faCircleQuestion,
  faCircleInfo,
  faCircleCheck,
  faCircleExclamation,
  faCircleXmark,
  faTriangleExclamation,
  faUpload,
  faDownload,
  faSun,
  faMoon,
  faRightFromBracket,
  faGear,
  faCopy,
  faTrash,
  faPenToSquare,
  faPlus,
  faMinus,
  faMagnifyingGlass,
  faRotate,
  faEye,
  faEyeSlash,
  faArrowUpRightFromSquare,

  // Nav route icons (one per page).
  faGauge,
  faBrain,
  faCubes,
  faDiagramProject,
  faFolderTree,
  faBuilding,
  faUsers,
  faPlug,
  faSliders,
  faMessage,
  faSatelliteDish,
  faKey,
  faFingerprint,
  faShareNodes,
  faPuzzlePiece,
  faDatabase,
  faListCheck,
  faCloudMoon,
  faChartLine,
  faFileImport,
  faUserAstronaut,
  faRightToBracket,
  faWandMagicSparkles,

  // Sidebar section icons.
  faStar,
  faTableCellsLarge,
  faPeopleGroup,
  faGears,
  faServer,
  faUser,

  // Empty-state and action icons.
  faSeedling,
  faFloppyDisk,
  faBolt,
  faTerminal,
} from "@fortawesome/free-solid-svg-icons";
