package service

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/nram-ai/nram/internal/model"
	"github.com/nram-ai/nram/internal/storage"
)

// ShareTokenService orchestrates share-token lifecycle operations across the
// share_tokens / share_token_grants storage and the oauth_* tables that bind
// derived credentials back to a share.
type ShareTokenService struct {
	shareRepo *storage.ShareTokenRepo
	oauthRepo *storage.OAuthRepo
}

// NewShareTokenService wires the share-token storage repo and the OAuth repo
// (needed for derived-binding listing and cascade-revoke on share revoke).
func NewShareTokenService(shareRepo *storage.ShareTokenRepo, oauthRepo *storage.OAuthRepo) *ShareTokenService {
	return &ShareTokenService{
		shareRepo: shareRepo,
		oauthRepo: oauthRepo,
	}
}

// ErrShareNotOwned is returned by Revoke / SetGrants when the caller is not
// the share's owner. Handlers should map this to HTTP 403, not 400.
var ErrShareNotOwned = errors.New("share not owned by caller")

// CreateRequest captures the owner-supplied parameters for a new share.
type CreateShareRequest struct {
	OwnerUserID uuid.UUID
	Name        string
	Description string
	IsOneShot   bool
	ExpiresAt   time.Time
	Grants      []model.ShareTokenGrant
}

// CreateShareResult is returned from Create. RawSecret is the wire-format
// nram_s_<hex> string; it must be shown to the owner exactly once and is
// never recoverable afterward.
type CreateShareResult struct {
	Share     *model.ShareToken
	RawSecret string
}

// Create issues a new share. Validates expiry is in the future, name is not
// empty, and the grant list is non-empty. The raw secret is generated by the
// repo (which performs the hash + insert atomically).
func (s *ShareTokenService) Create(ctx context.Context, req CreateShareRequest) (*CreateShareResult, error) {
	if req.OwnerUserID == uuid.Nil {
		return nil, errors.New("owner_user_id is required")
	}
	if req.Name == "" {
		return nil, errors.New("name is required")
	}
	if !req.ExpiresAt.After(time.Now().UTC()) {
		return nil, errors.New("expires_at must be in the future")
	}
	if len(req.Grants) == 0 {
		return nil, errors.New("at least one project grant is required")
	}

	share := &model.ShareToken{
		OwnerUserID: req.OwnerUserID,
		Name:        req.Name,
		Description: req.Description,
		IsOneShot:   req.IsOneShot,
		ExpiresAt:   req.ExpiresAt.UTC(),
	}

	// Set the share_token_id on every grant so the repo can insert them
	// against the same share id (the repo assigns share.ID before inserting).
	for i := range req.Grants {
		req.Grants[i].ShareTokenID = uuid.Nil // overwritten by repo via share.ID
	}

	raw, err := s.shareRepo.Create(ctx, share, req.Grants)
	if err != nil {
		return nil, fmt.Errorf("share token create: %w", err)
	}

	return &CreateShareResult{
		Share:     share,
		RawSecret: raw,
	}, nil
}

// Resolve validates the raw secret, looks up the share + grants, and applies
// the "must be active" rules. A one-shot share whose consumed_at is set is
// rejected (the credential is dead on bearer-direct, and the consent path
// must not mint a second OAuth chain). The OAuth-issued chain from the
// original redemption remains valid because refresh-token exchange does not
// re-call Resolve — the middleware re-resolves grants by share_token_id from
// the JWT/refresh row.
func (s *ShareTokenService) Resolve(ctx context.Context, rawSecret string) (*model.ShareToken, []model.ShareTokenGrant, error) {
	return s.shareRepo.ValidateBySecret(ctx, rawSecret)
}

// Revoke marks the share revoked and cascades a revocation across every
// refresh token minted under it. Existing access JWTs continue to validate
// at the JWT layer until they expire; the per-request middleware lookup
// against share_tokens.revoked_at is what kills active sessions immediately.
func (s *ShareTokenService) Revoke(ctx context.Context, ownerUserID, shareID uuid.UUID) error {
	share, err := s.shareRepo.GetByID(ctx, shareID)
	if err != nil {
		return err
	}
	if share.OwnerUserID != ownerUserID {
		return ErrShareNotOwned
	}
	if err := s.shareRepo.Revoke(ctx, shareID); err != nil {
		return err
	}
	if err := s.oauthRepo.RevokeRefreshTokensByShareToken(ctx, shareID); err != nil {
		return err
	}
	return nil
}

// SetGrants atomically replaces the grant set on a share. The owner-only
// check is enforced; passing zero grants is rejected at the repo (would
// auto-revoke the share, which the caller likely did not intend).
func (s *ShareTokenService) SetGrants(ctx context.Context, ownerUserID, shareID uuid.UUID, grants []model.ShareTokenGrant) error {
	share, err := s.shareRepo.GetByID(ctx, shareID)
	if err != nil {
		return err
	}
	if share.OwnerUserID != ownerUserID {
		return ErrShareNotOwned
	}
	return s.shareRepo.SetGrants(ctx, shareID, grants)
}

// ListByOwner returns the owner's shares, newest first.
func (s *ShareTokenService) ListByOwner(ctx context.Context, ownerUserID uuid.UUID) ([]model.ShareToken, error) {
	return s.shareRepo.ListByOwner(ctx, ownerUserID)
}

// ListGrants returns the project-permission grants attached to a share.
func (s *ShareTokenService) ListGrants(ctx context.Context, shareID uuid.UUID) ([]model.ShareTokenGrant, error) {
	return s.shareRepo.ListGrants(ctx, shareID)
}

// ListGrantsByOwner returns all grants for shares owned by the user, indexed
// by share id. One query — used by the share-list endpoint to avoid 1+N.
func (s *ShareTokenService) ListGrantsByOwner(ctx context.Context, ownerUserID uuid.UUID) (map[uuid.UUID][]model.ShareTokenGrant, error) {
	return s.shareRepo.ListGrantsByOwner(ctx, ownerUserID)
}

// ListBindings returns the OAuth clients that were minted under this share.
// Used by the share-detail UI to render derived bindings. Each binding has
// its own revoke control surfaced at the OAuth-client layer.
func (s *ShareTokenService) ListBindings(ctx context.Context, shareID uuid.UUID) ([]model.OAuthClient, error) {
	return s.oauthRepo.ListClientsByShareToken(ctx, shareID)
}

// MarkConsumed records the one-shot redemption side-effect. Called from the
// consent-flow handler immediately before the OAuth code is minted, so the
// share is locked even if the recipient never finishes the code exchange.
func (s *ShareTokenService) MarkConsumed(ctx context.Context, shareID uuid.UUID) error {
	return s.shareRepo.MarkConsumed(ctx, shareID)
}

// GetByID returns a share by primary key. The owner-only check is the
// caller's responsibility — this is the lookup primitive consumed by the
// REST handlers and the consent flow.
func (s *ShareTokenService) GetByID(ctx context.Context, id uuid.UUID) (*model.ShareToken, error) {
	return s.shareRepo.GetByID(ctx, id)
}

// SweepZeroGrantShares revokes any non-revoked share owned by ownerUserID
// whose grant set has gone empty (typically because every referenced
// project was deleted and the FK cascade dropped the grant rows). Called
// from the project-delete cascade post-commit. Refresh-token revocation
// runs against the freshly-revoked shares only — historical revokes are
// already cascaded and re-walking them on every project delete would scale
// with the owner's lifetime revoke history.
func (s *ShareTokenService) SweepZeroGrantShares(ctx context.Context, ownerUserID uuid.UUID) (int, error) {
	freshlyRevoked, err := s.shareRepo.RevokeZeroGrantSharesForOwner(ctx, ownerUserID)
	if err != nil {
		return 0, err
	}
	for _, id := range freshlyRevoked {
		if err := s.oauthRepo.RevokeRefreshTokensByShareToken(ctx, id); err != nil {
			return len(freshlyRevoked), err
		}
	}
	return len(freshlyRevoked), nil
}
